from pydantic import BaseModel
from typing import Optional, List

# ------------------------------------------------------------
# Model: EmployeeAddress
# Description:
#   Represents an employee's address record.
#   Stores address details linked to a specific employee.
# ------------------------------------------------------------
class EmployeeAddress(BaseModel):
    id: Optional[int] = None           # Unique address ID (optional, auto-generated by DB)
    employee_id: int                   # Employee ID this address belongs to
    address: str                       # Street or detailed address line
    city: str                          # City name
    state: str                         # State or province
    zip_code: str                      # Postal or ZIP code
    is_default: bool = False           # Marks this address as the default
